version: '3.8'

services:
  gear:
    build: ./business_logic/Gear
    ports:
      - "5004:5004"
    depends_on:
      - adapter_layer
      - data_layer
    networks:
      gearup_app-network:
        aliases:
          - gear

  huts:
    build: ./business_logic/Huts
    ports:
      - "5003:5003"
    depends_on:
      - adapter_layer
    networks:
      gearup_app-network:
        aliases:
          - huts

  trails:
    build: ./business_logic/Trails
    ports:
      - "5002:5002"
    depends_on:
      - adapter_layer
    networks:
      gearup_app-network:
        aliases:
          - trails

  weather:
    build: ./business_logic/Weather
    ports:
      - "5001:5001"
    depends_on:
      - adapter_layer
    networks:
      gearup_app-network:
        aliases:
          - weather

  adapter_layer:
    build: ./adapter_layer
    ports:
      - "5050:5050"
    networks:
      gearup_app-network:
        aliases:
          - adapter_layer

  data_layer:
    build: ./data_layer
    ports:
      - "5051:5051"
    networks:
      gearup_app-network:
        aliases:
          - data_layer

  process_centric:
    build: ./process_centric
    ports:
      - "5000:5000"
    depends_on:
      - adapter_layer
      - gear
      - huts
      - trails
      - weather
      - data_layer
      - redis  
    networks:
      gearup_app-network:
        aliases:
          - process_centric

  redis:
    image: redis
    ports:
      - "6379:6379"  
    networks:
      gearup_app-network:
        aliases:
          - redis

networks:
  gearup_app-network:
    driver: bridge
