"""empty message

Revision ID: 4cd6b5374629
Revises: 
Create Date: 2024-08-28 19:19:42.408153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd6b5374629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gender', sa.CHAR(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('warmth', sa.String(), nullable=False),
    sa.Column('waterproof', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('favourite_gear',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gearid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['gearid'], ['gear.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'gearid', name='uix_email_gearid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_gear')
    op.drop_table('users')
    op.drop_table('gear')
    # ### end Alembic commands ###
