ADAPTER_LAYER_URL = "http://127.0.0.1:5050"

COORDS_URL = ADAPTER_LAYER_URL + '/coordinates'
ROUTE_URL = ADAPTER_LAYER_URL + '/trails'
ELEVATION_URL = ADAPTER_LAYER_URL + '/elevation'
TRAILIMAGE_URL = ADAPTER_LAYER_URL + '/trailimage'